(function(){var t=window.AmCharts
t.AmRectangularChart=t.Class({inherits:t.AmCoordinateChart,construct:function(i){t.AmRectangularChart.base.construct.call(this,i),this.theme=i,this.createEvents("zoomed","changed"),this.marginRight=this.marginBottom=this.marginTop=this.marginLeft=20,this.depth3D=this.angle=0,this.plotAreaFillColors="#FFFFFF",this.plotAreaFillAlphas=0,this.plotAreaBorderColor="#000000",this.plotAreaBorderAlpha=0,this.maxZoomFactor=20,this.zoomOutButtonImageSize=19,this.zoomOutButtonImage="lens",this.zoomOutText="Show all",this.zoomOutButtonColor="#e5e5e5",this.zoomOutButtonAlpha=0,this.zoomOutButtonRollOverAlpha=1,this.zoomOutButtonPadding=8,this.trendLines=[],this.autoMargins=!0,this.marginsUpdated=!1,this.autoMarginOffset=10,t.applyTheme(this,i,"AmRectangularChart")},initChart:function(){t.AmRectangularChart.base.initChart.call(this),this.updateDxy(),!this.marginsUpdated&&this.autoMargins&&(this.resetMargins(),this.drawGraphs=!1),this.processScrollbars(),this.updateMargins(),this.updatePlotArea(),this.updateScrollbars(),this.updateTrendLines(),this.updateChartCursor(),this.updateValueAxes(),this.scrollbarOnly||this.updateGraphs()},drawChart:function(){if(t.AmRectangularChart.base.drawChart.call(this),this.drawPlotArea(),t.ifArray(this.chartData)){var i=this.chartCursor
i&&i.draw()}},resetMargins:function(){var t,i={}
if("xy"==this.type){var e=this.xAxes,a=this.yAxes
for(t=0;t<e.length;t++){var s=e[t]
s.ignoreAxisWidth||(s.setOrientation(!0),s.fixAxisPosition(),i[s.position]=!0)}for(t=0;t<a.length;t++)e=a[t],e.ignoreAxisWidth||(e.setOrientation(!1),e.fixAxisPosition(),i[e.position]=!0)}else{for(a=this.valueAxes,t=0;t<a.length;t++)e=a[t],e.ignoreAxisWidth||(e.setOrientation(this.rotate),e.fixAxisPosition(),i[e.position]=!0);(t=this.categoryAxis)&&!t.ignoreAxisWidth&&(t.setOrientation(!this.rotate),t.fixAxisPosition(),t.fixAxisPosition(),i[t.position]=!0)}i.left&&(this.marginLeft=0),i.right&&(this.marginRight=0),i.top&&(this.marginTop=0),i.bottom&&(this.marginBottom=0),this.fixMargins=i},measureMargins:function(){var t,i,e=this.valueAxes,a=this.autoMarginOffset,s=this.fixMargins,h=this.realWidth,o=this.realHeight,r=a,n=a,l=h
for(t=o,i=0;i<e.length;i++)e[i].handleSynchronization(),t=this.getAxisBounds(e[i],r,l,n,t),r=Math.round(t.l),l=Math.round(t.r),n=Math.round(t.t),t=Math.round(t.b);(e=this.categoryAxis)&&(t=this.getAxisBounds(e,r,l,n,t),r=Math.round(t.l),l=Math.round(t.r),n=Math.round(t.t),t=Math.round(t.b)),s.left&&r<a&&(this.marginLeft=Math.round(-r+a),!isNaN(this.minMarginLeft)&&this.marginLeft<this.minMarginLeft&&(this.marginLeft=this.minMarginLeft)),s.right&&l>=h-a&&(this.marginRight=Math.round(l-h+a),!isNaN(this.minMarginRight)&&this.marginRight<this.minMarginRight&&(this.marginRight=this.minMarginRight)),s.top&&n<a+this.titleHeight&&(this.marginTop=Math.round(this.marginTop-n+a+this.titleHeight),!isNaN(this.minMarginTop)&&this.marginTop<this.minMarginTop&&(this.marginTop=this.minMarginTop)),s.bottom&&t>o-a&&(this.marginBottom=Math.round(this.marginBottom+t-o+a),!isNaN(this.minMarginBottom)&&this.marginBottom<this.minMarginBottom&&(this.marginBottom=this.minMarginBottom)),this.initChart()},getAxisBounds:function(t,i,e,a,s){if(!t.ignoreAxisWidth){var h=t.labelsSet,o=t.tickLength
if(t.inside&&(o=0),h)switch(h=t.getBBox(),t.position){case"top":a>(t=h.y)&&(a=t)
break
case"bottom":s<(t=h.y+h.height)&&(s=t)
break
case"right":e<(t=h.x+h.width+o+3)&&(e=t)
break
case"left":i>(t=h.x-o)&&(i=t)}}return{l:i,t:a,r:e,b:s}},drawZoomOutButton:function(){var i=this
if(!i.zbSet){var e=i.container.set()
i.zoomButtonSet.push(e)
var a,s=i.color,h=i.fontSize,o=i.zoomOutButtonImageSize,r=i.zoomOutButtonImage.replace(/\.[a-z]*$/i,""),n=i.langObj.zoomOutText||i.zoomOutText,l=i.zoomOutButtonColor,d=i.zoomOutButtonAlpha,u=i.zoomOutButtonFontSize,c=i.zoomOutButtonPadding
isNaN(u)||(h=u),(u=i.zoomOutButtonFontColor)&&(s=u),(u=i.zoomOutButton)&&(u.fontSize&&(h=u.fontSize),u.color&&(s=u.color),u.backgroundColor&&(l=u.backgroundColor),isNaN(u.backgroundAlpha)||(i.zoomOutButtonRollOverAlpha=u.backgroundAlpha))
var m=u=0
m=i.pathToImages
for(r&&((t.isAbsolute(r)||void 0===m)&&(m=""),a=i.container.image(m+r+i.extension,0,0,o,o),t.setCN(i,a,"zoom-out-image"),e.push(a),u=(a=a.getBBox()).width+5),void 0!==n&&(s=t.text(i.container,n,s,i.fontFamily,h,"start"),t.setCN(i,s,"zoom-out-label"),h=s.getBBox(),m=a?a.height/2-3:h.height/2,s.translate(u,m),e.push(s)),a=e.getBBox(),s=1,t.isModern||(s=0),(l=t.rect(i.container,a.width+2*c+5,a.height+2*c-2,l,1,1,l,s)).setAttr("opacity",d),l.translate(-c,-c),t.setCN(i,l,"zoom-out-bg"),e.push(l),l.toBack(),i.zbBG=l,a=l.getBBox(),e.translate(i.marginLeftReal+i.plotAreaWidth-a.width+c,i.marginTopReal+c),e.hide(),e.mouseover(function(){i.rollOverZB()}).mouseout(function(){i.rollOutZB()}).click(function(){i.clickZB()}).touchstart(function(){i.rollOverZB()}).touchend(function(){i.rollOutZB(),i.clickZB()}),d=0;d<e.length;d++)e[d].attr({cursor:"pointer"})
void 0!==i.zoomOutButtonTabIndex&&(e.setAttr("tabindex",i.zoomOutButtonTabIndex),e.setAttr("role","menuitem"),e.keyup(function(t){13==t.keyCode&&i.clickZB()})),i.zbSet=e}},rollOverZB:function(){this.rolledOverZB=!0,this.zbBG.setAttr("opacity",this.zoomOutButtonRollOverAlpha)},rollOutZB:function(){this.rolledOverZB=!1,this.zbBG.setAttr("opacity",this.zoomOutButtonAlpha)},clickZB:function(){this.rolledOverZB=!1,this.zoomOut()},zoomOut:function(){this.zoomOutValueAxes()},drawPlotArea:function(){var i=this.dx,e=this.dy,a=this.marginLeftReal,s=this.marginTopReal,h=this.plotAreaWidth-1,o=this.plotAreaHeight-1,r=this.plotAreaFillColors,n=this.plotAreaFillAlphas,l=this.plotAreaBorderColor,d=this.plotAreaBorderAlpha
"object"==typeof n&&(n=n[0]),r=t.polygon(this.container,[0,h,h,0,0],[0,0,o,o,0],r,n,1,l,d,this.plotAreaGradientAngle),t.setCN(this,r,"plot-area"),r.translate(a+i,s+e),this.set.push(r),0!==i&&0!==e&&("object"==typeof(r=this.plotAreaFillColors)&&(r=r[0]),r=t.adjustLuminosity(r,-.15),h=t.polygon(this.container,[0,i,h+i,h,0],[0,e,e,0,0],r,n,1,l,d),t.setCN(this,h,"plot-area-bottom"),h.translate(a,s+o),this.set.push(h),i=t.polygon(this.container,[0,0,i,i,0],[0,o,o+e,e,0],r,n,1,l,d),t.setCN(this,i,"plot-area-left"),i.translate(a,s),this.set.push(i)),(a=this.bbset)&&this.scrollbarOnly&&a.remove()},updatePlotArea:function(){var t=this.updateWidth(),i=this.updateHeight(),e=this.container
this.realWidth=t,this.realWidth=i,e&&this.container.setSize(t,i)
e=this.marginLeftReal
var a=this.marginTopReal
t=t-e-this.marginRightReal-this.dx,i=i-a-this.marginBottomReal
1>t&&(t=1),1>i&&(i=1),this.plotAreaWidth=Math.round(t),this.plotAreaHeight=Math.round(i),this.plotBalloonsSet.translate(e,a)},updateDxy:function(){this.dx=Math.round(this.depth3D*Math.cos(this.angle*Math.PI/180)),this.dy=Math.round(-this.depth3D*Math.sin(this.angle*Math.PI/180)),this.d3x=Math.round(this.columnSpacing3D*Math.cos(this.angle*Math.PI/180)),this.d3y=Math.round(-this.columnSpacing3D*Math.sin(this.angle*Math.PI/180))},updateMargins:function(){var t=this.getTitleHeight()
this.titleHeight=t,this.marginTopReal=this.marginTop-this.dy,this.fixMargins&&!this.fixMargins.top&&(this.marginTopReal+=t),this.marginBottomReal=this.marginBottom,this.marginLeftReal=this.marginLeft,this.marginRightReal=this.marginRight},updateValueAxes:function(){var t,i=this.valueAxes
for(t=0;t<i.length;t++){var e=i[t]
this.setAxisRenderers(e),this.updateObjectSize(e)}},setAxisRenderers:function(i){i.axisRenderer=t.RecAxis,i.guideFillRenderer=t.RecFill,i.axisItemRenderer=t.RecItem,i.marginsChanged=!0},updateGraphs:function(){var t,i=this.graphs
for(t=0;t<i.length;t++){var e=i[t]
e.index=t,e.rotate=this.rotate,this.updateObjectSize(e)}},updateObjectSize:function(t){t.width=this.plotAreaWidth-1,t.height=this.plotAreaHeight-1,t.x=this.marginLeftReal,t.y=this.marginTopReal,t.dx=this.dx,t.dy=this.dy},updateChartCursor:function(){var i=this.chartCursor
i&&(i=t.processObject(i,t.ChartCursor,this.theme),this.updateObjectSize(i),this.addChartCursor(i),i.chart=this)},processScrollbars:function(){var i=this.chartScrollbar
i&&(i=t.processObject(i,t.ChartScrollbar,this.theme),this.addChartScrollbar(i))},updateScrollbars:function(){},removeChartCursor:function(){t.callMethod("destroy",[this.chartCursor]),this.chartCursor=null},zoomTrendLines:function(){var t,i=this.trendLines
for(t=0;t<i.length;t++){var e=i[t]
e.valueAxis.recalculateToPercents?e.set&&e.set.hide():(e.x=this.marginLeftReal,e.y=this.marginTopReal,e.draw())}},handleCursorValueZoom:function(){},addTrendLine:function(t){this.trendLines.push(t)},zoomOutValueAxes:function(){for(var t=this.valueAxes,i=0;i<t.length;i++)t[i].zoomOut()},removeTrendLine:function(t){var i,e=this.trendLines
for(i=e.length-1;0<=i;i--)e[i]==t&&e.splice(i,1)},adjustMargins:function(t,i){var e=t.position,a=t.scrollbarHeight+t.offset
t.enabled&&("top"==e?i?this.marginLeftReal+=a:this.marginTopReal+=a:i?this.marginRightReal+=a:this.marginBottomReal+=a)},getScrollbarPosition:function(t,i,e){var a="bottom",s="top"
t.oppositeAxis||(s=a,a="top"),t.position=i?"bottom"==e||"left"==e?a:s:"top"==e||"right"==e?a:s},updateChartScrollbar:function(t,i){if(t){t.rotate=i
var e=this.marginTopReal,a=this.marginLeftReal,s=t.scrollbarHeight,h=this.dx,o=this.dy,r=t.offset
"top"==t.position?i?(t.y=e,t.x=a-s-r):(t.y=e-s+o-r,t.x=a+h):i?(t.y=e+o,t.x=a+this.plotAreaWidth+h+r):(t.y=e+this.plotAreaHeight+r,t.x=this.marginLeftReal)}},showZB:function(t){var i=this.zbSet
t&&(""!==(i=this.zoomOutText)&&i&&this.drawZoomOutButton()),(i=this.zbSet)&&(this.zoomButtonSet.push(i),t?i.show():i.hide(),this.rollOutZB())},handleReleaseOutside:function(i){t.AmRectangularChart.base.handleReleaseOutside.call(this,i),(i=this.chartCursor)&&i.handleReleaseOutside&&i.handleReleaseOutside()},handleMouseDown:function(i){t.AmRectangularChart.base.handleMouseDown.call(this,i)
var e=this.chartCursor
e&&e.handleMouseDown&&!this.rolledOverZB&&e.handleMouseDown(i)},update:function(){t.AmRectangularChart.base.update.call(this),this.chartCursor&&this.chartCursor.update&&this.chartCursor.update()},handleScrollbarValueZoom:function(t){this.relativeZoomValueAxes(t.target.valueAxes,t.relativeStart,t.relativeEnd),this.zoomAxesAndGraphs()},zoomValueScrollbar:function(t){if(t&&t.enabled){var i=t.valueAxes[0],e=i.relativeStart,a=i.relativeEnd
i.reversed&&(a=1-e,e=1-i.relativeEnd),t.percentZoom(e,a)}},zoomAxesAndGraphs:function(){if(!this.scrollbarOnly){var t,i=this.valueAxes
for(t=0;t<i.length;t++)i[t].zoom(this.start,this.end)
for(i=this.graphs,t=0;t<i.length;t++)i[t].zoom(this.start,this.end);(t=this.chartCursor)&&t.clearSelection(),this.zoomTrendLines()}},handleValueAxisZoomReal:function(t,i){if((a=t.relativeStart)>(s=t.relativeEnd))var e=a,a=s,s=e
this.relativeZoomValueAxes(i,a,s),this.updateAfterValueZoom()},updateAfterValueZoom:function(){this.zoomAxesAndGraphs(),this.zoomScrollbar()},relativeZoomValueAxes:function(i,e,a){if(this.hideBalloonReal(),(e=t.fitToBounds(e,0,1))>(a=t.fitToBounds(a,0,1))){var s=e
e=a,a=s}s=1/this.maxZoomFactor
var h=t.getDecimals(s)+4
if(a-e<s&&(e=(a=e+(a-e)/2)-s/2,1<(a+=s/2)&&(e-=a-1,a=1),0>e&&(e=0,a=s)),e=t.roundTo(e,h),a=t.roundTo(a,h),s=!1,i){for(h=0;h<i.length;h++){var o=i[h].zoomToRelativeValues(e,a,!0)
o&&(s=o)}this.showZB()}return s},addChartCursor:function(i){t.callMethod("destroy",[this.chartCursor]),i&&(this.listenTo(i,"moved",this.handleCursorMove),this.listenTo(i,"zoomed",this.handleCursorZoom),this.listenTo(i,"zoomStarted",this.handleCursorZoomStarted),this.listenTo(i,"panning",this.handleCursorPanning),this.listenTo(i,"onHideCursor",this.handleCursorHide)),this.chartCursor=i},handleCursorChange:function(){},handleCursorMove:function(t){var i,e=this.valueAxes
for(i=0;i<e.length;i++)if(!t.panning){var a=e[i]
a&&a.showBalloon&&a.showBalloon(t.x,t.y)}},handleCursorZoom:function(t){if(this.skipZoomed)this.skipZoomed=!1
else{var i=this.startX0,e=this.endX0,a=this.endY0,s=this.startY0,h=t.startX,o=t.endX,r=t.startY,n=t.endY
this.startX0=this.endX0=this.startY0=this.endY0=NaN,this.handleCursorZoomReal(i+h*(e-i),i+o*(e-i),s+r*(a-s),s+n*(a-s),t)}},handleCursorHide:function(){var t,i=this.valueAxes
for(t=0;t<i.length;t++)i[t].hideBalloon()
for(i=this.graphs,t=0;t<i.length;t++)i[t].hideBalloonReal()}})})(),function(){var t=window.AmCharts
t.AmSerialChart=t.Class({inherits:t.AmRectangularChart,construct:function(i){this.type="serial",t.AmSerialChart.base.construct.call(this,i),this.cname="AmSerialChart",this.theme=i,this.columnSpacing=5,this.columnSpacing3D=0,this.columnWidth=.8
var e=new t.CategoryAxis(i)
e.chart=this,this.categoryAxis=e,this.zoomOutOnDataUpdate=!0,this.mouseWheelZoomEnabled=this.mouseWheelScrollEnabled=this.rotate=this.skipZoom=!1,this.minSelectedTime=0,t.applyTheme(this,i,this.cname)},initChart:function(){t.AmSerialChart.base.initChart.call(this),this.updateCategoryAxis(this.categoryAxis,this.rotate,"categoryAxis"),this.dataChanged?this.parseData():this.onDataUpdated(),this.drawGraphs=!0},onDataUpdated:function(){var t,i=this.countColumns(),e=this.chartData,a=this.graphs
for(t=0;t<a.length;t++){var s=a[t]
s.data=e,s.columnCount=i}0<e.length&&(this.firstTime=this.getStartTime(e[0].time),this.lastTime=this.getEndTime(e[e.length-1].time)),this.drawChart(),this.autoMargins&&!this.marginsUpdated?(this.marginsUpdated=!0,this.measureMargins()):this.dispDUpd()},syncGrid:function(){if(this.synchronizeGrid){var i,e,a=this.valueAxes
if(0<a.length){var s=0
for(e=0;e<a.length;e++)i=a[e],s<i.gridCountReal&&(s=i.gridCountReal)
var h=!1
for(e=0;e<a.length;e++)if(i=a[e],i.gridCountReal<s){var o=(s-i.gridCountReal)/2,r=h=o
0!=o-Math.round(o)&&(h-=.5,r+=.5),0<=i.min&&0>i.min-h*i.step&&(r+=h,h=0),0>=i.max&&0<i.max+r*i.step&&(h+=r,r=0),o=t.getDecimals(i.step),i.minimum=t.roundTo(i.min-h*i.step,o),i.maximum=t.roundTo(i.max+r*i.step,o),i.setStep=i.step,h=i.strictMinMax=!0}for(h&&this.updateAfterValueZoom(),e=0;e<a.length;e++)i=a[e],i.minimum=NaN,i.maximum=NaN,i.setStep=NaN,i.strictMinMax=!1}}},handleWheelReal:function(t,i){if(!this.wheelBusy){var e=this.categoryAxis,a=e.parseDates,s=e.minDuration(),h=1,o=1
if(this.mouseWheelZoomEnabled?i||(h=-1):i&&(h=-1),n=this.chartCursor)if(n.mouseIsOver()){var r=n.mouseX,n=n.mouseY
h!=o&&(h*=r=this.rotate?n/this.plotAreaHeight:r/this.plotAreaWidth,o*=1-r),r=.05*(this.end-this.start),a&&(r=.05*(this.endTime-this.startTime)/s),1>r&&(r=1),h*=r,o*=r,a&&!e.equalSpacing||(h=Math.round(h),o=Math.round(o)),n=this.chartData.length,e=this.lastTime,r=this.firstTime,0>t?a?(n=this.endTime-this.startTime,a=this.startTime+h*s,s=this.endTime+o*s,0<o&&0<h&&s>=e&&(s=e,a=e-n),this.zoomToDates(new Date(a),new Date(s))):(0<o&&0<h&&this.end>=n-1&&(h=o=0),a=this.start+h,s=this.end+o,this.zoomToIndexes(a,s)):a?(n=this.endTime-this.startTime,a=this.startTime-h*s,s=this.endTime-o*s,0<o&&0<h&&a<=r&&(a=r,s=r+n),this.zoomToDates(new Date(a),new Date(s))):(0<o&&0<h&&1>this.start&&(h=o=0),a=this.start-h,s=this.end-o,this.zoomToIndexes(a,s))}else this.handleMouseOut()}},validateData:function(i){this.marginsUpdated=!1,this.zoomOutOnDataUpdate&&!i&&(this.endTime=this.end=this.startTime=this.start=NaN)
var e=i=!1,a=!1,s=this.chartScrollbar
s&&(s.dragging&&(i=!0,s.handleDragStop()),s.resizingRight&&(a=!0,s.rightDragStop()),s.resizingLeft&&(e=!0,s.leftDragStop())),t.AmSerialChart.base.validateData.call(this),i&&s.handleDragStart(),a&&s.rightDragStart(),e&&s.leftDragStart()},drawChart:function(){if(0<this.realWidth&&0<this.realHeight){t.AmSerialChart.base.drawChart.call(this)
var i=this.chartData
if(t.ifArray(i)){!(s=this.chartScrollbar)||!this.marginsUpdated&&this.autoMargins||s.draw(),(s=this.valueScrollbar)&&s.draw()
var e,a,s=i.length-1;(e=this.categoryAxis).parseDates&&!e.equalSpacing?(e=this.startTime,a=this.endTime,(isNaN(e)||isNaN(a))&&(e=this.firstTime,a=this.lastTime)):(e=this.start,a=this.end,(isNaN(e)||isNaN(a))&&(a=e=NaN),isNaN(e)&&(isNaN(this.startTime)||(e=this.getClosestIndex(i,"time",this.startTime,!0,0,i.length))),isNaN(a)&&(isNaN(this.endTime)||(a=this.getClosestIndex(i,"time",this.endTime,!1,0,i.length))),(isNaN(e)||isNaN(a))&&(e=0,a=s)),this.endTime=this.startTime=this.end=this.start=void 0,this.zoom(e,a)}}else this.cleanChart()},cleanChart:function(){t.callMethod("destroy",[this.valueAxes,this.graphs,this.categoryAxis,this.chartScrollbar,this.chartCursor,this.valueScrollbar])},updateCategoryAxis:function(t,i,e){t.chart=this,t.id=e,t.rotate=i,t.setOrientation(!this.rotate),t.init(),this.setAxisRenderers(t),this.updateObjectSize(t)},updateValueAxes:function(){t.AmSerialChart.base.updateValueAxes.call(this)
var i,e=this.valueAxes
for(i=0;i<e.length;i++){var a=e[i],s=this.rotate
a.rotate=s,a.setOrientation(s),(s=this.categoryAxis).startOnAxis&&!s.parseDates||(a.expandMinMax=!0)}},getStartTime:function(i){var e=this.categoryAxis
return t.resetDateToMin(new Date(i),e.minPeriod,1,e.firstDayOfWeek).getTime()},getEndTime:function(i){var e=t.extractPeriod(this.categoryAxis.minPeriod)
return t.changeDate(new Date(i),e.period,e.count,!0).getTime()-1},updateMargins:function(){t.AmSerialChart.base.updateMargins.call(this)
var i=this.chartScrollbar
i&&(this.getScrollbarPosition(i,this.rotate,this.categoryAxis.position),this.adjustMargins(i,this.rotate)),(i=this.valueScrollbar)&&(this.getScrollbarPosition(i,!this.rotate,this.valueAxes[0].position),this.adjustMargins(i,!this.rotate))},updateScrollbars:function(){t.AmSerialChart.base.updateScrollbars.call(this),this.updateChartScrollbar(this.chartScrollbar,this.rotate),this.updateChartScrollbar(this.valueScrollbar,!this.rotate)},zoom:function(t,i){var e=this.categoryAxis
e.parseDates&&!e.equalSpacing?(this.timeZoom(t,i),isNaN(t)&&this.zoomOutValueAxes()):this.indexZoom(t,i),(e=this.chartCursor)&&(e.pan||e.hideCursorReal()),this.updateLegendValues()},timeZoom:function(i,e){var a=this.maxSelectedTime
if(isNaN(a)||(e!=this.endTime&&e-i>a&&(i=e-a),i!=this.startTime&&e-i>a&&(e=i+a)),0<(s=this.minSelectedTime)&&e-i<s){var s,h=Math.round(i+(e-i)/2)
i=h-(s=Math.round(s/2)),e=h+s}if(s=this.chartData,h=this.categoryAxis,t.ifArray(s)&&(i!=this.startTime||e!=this.endTime)){var o=h.minDuration(),r=this.firstTime,n=this.lastTime
i||(i=r,isNaN(a)||(i=n-a)),e||(e=n),i>n&&(i=n),e<r&&(e=r),i<r&&(i=r),e>n&&(e=n),e<i&&(e=i+o),e-i<o/5&&(e<n?e=i+o/5:i=e-o/5),this.startTime=i,this.endTime=e,a=s.length-1,o=this.getClosestIndex(s,"time",i,!0,0,a),s=this.getClosestIndex(s,"time",e,!1,o,a),h.timeZoom(i,e),h.zoom(o,s),this.start=t.fitToBounds(o,0,a),this.end=t.fitToBounds(s,0,a),this.zoomAxesAndGraphs(),this.zoomScrollbar(),this.fixCursor(),this.showZB(),this.syncGrid(),this.updateColumnsDepth(),this.dispatchTimeZoomEvent()}},showZB:function(){var i,e=this.categoryAxis
e&&e.parseDates&&!e.equalSpacing&&(this.startTime>this.firstTime&&(i=!0),this.endTime<this.lastTime&&(i=!0)),0<this.start&&(i=!0),this.end<this.chartData.length-1&&(i=!0),(e=this.valueAxes)&&(e=e[0],isNaN(e.relativeStart)||(0!==t.roundTo(e.relativeStart,3)&&(i=!0),1!=t.roundTo(e.relativeEnd,3)&&(i=!0))),t.AmSerialChart.base.showZB.call(this,i)},updateAfterValueZoom:function(){t.AmSerialChart.base.updateAfterValueZoom.call(this),this.updateColumnsDepth()},indexZoom:function(t,i){var e=this.maxSelectedSeries,a=!1
if(isNaN(e)||(i!=this.end&&i-t>e&&(t=i-e,a=!0),t!=this.start&&i-t>e&&(i=t+e,a=!0)),a&&(a=this.chartScrollbar)&&a.dragger){var s=a.dragger.getBBox()
a.maxWidth=s.width,a.maxHeight=s.height}t==this.start&&i==this.end||(a=this.chartData.length-1,isNaN(t)&&(t=0,isNaN(e)||(t=a-e)),isNaN(i)&&(i=a),i<t&&(i=t),i>a&&(i=a),t>a&&(t=a-1),0>t&&(t=0),this.start=t,this.end=i,this.categoryAxis.zoom(t,i),this.zoomAxesAndGraphs(),this.zoomScrollbar(),this.fixCursor(),0!==t||i!=this.chartData.length-1?this.showZB(!0):this.showZB(!1),this.syncGrid(),this.updateColumnsDepth(),this.dispatchIndexZoomEvent())},updateGraphs:function(){t.AmSerialChart.base.updateGraphs.call(this)
var i,e=this.graphs
for(i=0;i<e.length;i++){var a=e[i]
a.columnWidthReal=this.columnWidth,a.categoryAxis=this.categoryAxis,t.isString(a.fillToGraph)&&(a.fillToGraph=this.graphsById[a.fillToGraph])}},zoomAxesAndGraphs:function(){t.AmSerialChart.base.zoomAxesAndGraphs.call(this),this.updateColumnsDepth()},updateColumnsDepth:function(){if(0!==this.depth3D||0!==this.angle){var i,e,a=this.graphs
for(this.columnsArray=[],i=0;i<a.length;i++){var s,h=(e=a[i]).columnsArray
if(h)for(s=0;s<h.length;s++)this.columnsArray.push(h[s])}if(this.columnsArray.sort(this.compareDepth),a=this.columnsSet,0<this.columnsArray.length){for(h=this.container.set(),this.columnSet.push(h),i=0;i<this.columnsArray.length;i++)h.push(this.columnsArray[i].column.set)
e&&h.translate(e.x,e.y),this.columnsSet=h}t.remove(a)}},compareDepth:function(t,i){return t.depth>i.depth?1:-1},zoomScrollbar:function(){var t=this.chartScrollbar,i=this.categoryAxis
if(t){if(!this.zoomedByScrollbar){var e=t.dragger
e&&e.stop()}this.zoomedByScrollbar=!1,i.parseDates&&!i.equalSpacing?t.timeZoom(this.startTime,this.endTime):t.zoom(this.start,this.end)}this.zoomValueScrollbar(this.valueScrollbar)},updateTrendLines:function(){var i,e=this.trendLines
for(i=0;i<e.length;i++){var a=e[i]
a=t.processObject(a,t.TrendLine,this.theme)
e[i]=a,a.chart=this,a.id||(a.id="trendLineAuto"+i+"_"+(new Date).getTime()),t.isString(a.valueAxis)&&(a.valueAxis=this.getValueAxisById(a.valueAxis)),a.valueAxis||(a.valueAxis=this.valueAxes[0]),a.categoryAxis=this.categoryAxis}},validateNow:function(i,e){i&&this.zoomOutOnDataUpdate&&(this.endTime=this.end=this.startTime=this.start=NaN),t.AmSerialChart.base.validateNow.call(this,i,e)},countColumns:function(){var t,i,e,a,s=0,h=this.valueAxes.length,o=this.graphs.length,r=!1
for(a=0;a<h;a++){var n=(i=this.valueAxes[a]).stackType,l=0
if("100%"==n||"regular"==n)for(r=!1,e=0;e<o;e++)t=this.graphs[e],t.tcc=1,t.valueAxis==i&&"column"==t.type&&(!r&&t.stackable&&(s++,r=!0),(!t.stackable&&t.clustered||t.newStack&&0!==l)&&s++,t.columnIndex=s-1,t.clustered||(t.columnIndex=0),l++)
if("none"==n||"3d"==n){for(l=!1,e=0;e<o;e++)t=this.graphs[e],t.valueAxis==i&&"column"==t.type&&(t.clustered?(t.tcc=1,t.newStack&&(s=0),t.hidden||(t.columnIndex=s,s++)):t.hidden||(l=!0,t.tcc=1,t.columnIndex=0))
l&&0===s&&(s=1)}if("3d"==n){for(i=1,l=0;l<o;l++)t=this.graphs[l],t.newStack&&i++,t.depthCount=i,t.tcc=s
s=i}if("regular"==n||"100%"==n)for(i=10,l=0;l<o;l++)t=this.graphs[l],t.newStack&&i--,t.depthCount=i,t.tcc=s}return s},parseData:function(){t.AmSerialChart.base.parseData.call(this),this.parseSerialData(this.dataProvider)},getCategoryIndexByValue:function(t){var i,e=this.chartData
for(i=0;i<e.length;i++)if(e[i].category==t)return i},handleScrollbarZoom:function(t){this.zoomedByScrollbar=!0,this.zoom(t.start,t.end)},dispatchTimeZoomEvent:function(){if(this.drawGraphs&&(this.prevStartTime!=this.startTime||this.prevEndTime!=this.endTime)){var i={type:"zoomed"}
i.startDate=new Date(this.startTime),i.endDate=new Date(this.endTime),i.startIndex=this.start,i.endIndex=this.end,this.startIndex=this.start,this.endIndex=this.end,this.startDate=i.startDate,this.endDate=i.endDate,this.prevStartTime=this.startTime,this.prevEndTime=this.endTime
var e=this.categoryAxis,a=t.extractPeriod(e.minPeriod).period
e=e.dateFormatsObject[a]
i.startValue=t.formatDate(i.startDate,e,this),i.endValue=t.formatDate(i.endDate,e,this),i.chart=this,i.target=this,this.fire(i)}},dispatchIndexZoomEvent:function(){if(this.drawGraphs&&(this.prevStartIndex!=this.start||this.prevEndIndex!=this.end)){this.startIndex=this.start,this.endIndex=this.end
var i=this.chartData
if(t.ifArray(i)&&!isNaN(this.start)&&!isNaN(this.end)){var e={chart:this,target:this,type:"zoomed"}
e.startIndex=this.start,e.endIndex=this.end,e.startValue=i[this.start].category,e.endValue=i[this.end].category,this.categoryAxis.parseDates&&(this.startTime=i[this.start].time,this.endTime=i[this.end].time,e.startDate=new Date(this.startTime),e.endDate=new Date(this.endTime)),this.prevStartIndex=this.start,this.prevEndIndex=this.end,this.fire(e)}}},updateLegendValues:function(){this.legend&&this.legend.updateValues()},getClosestIndex:function(t,i,e,a,s,h){0>s&&(s=0),h>t.length-1&&(h=t.length-1)
var o=s+Math.round((h-s)/2),r=t[o][i]
return e==r?o:1>=h-s?a?s:Math.abs(t[s][i]-e)<Math.abs(t[h][i]-e)?s:h:e==r?o:e<r?this.getClosestIndex(t,i,e,a,s,o):this.getClosestIndex(t,i,e,a,o,h)},zoomToIndexes:function(t,i){var e=this.chartData
if(e){var a=e.length
0<a&&(0>t&&(t=0),i>a-1&&(i=a-1),(a=this.categoryAxis).parseDates&&!a.equalSpacing?this.zoom(e[t].time,this.getEndTime(e[i].time)):this.zoom(t,i))}},zoomToDates:function(i,e){var a=this.chartData
if(a)if(this.categoryAxis.equalSpacing){var s=this.getClosestIndex(a,"time",i.getTime(),!0,0,a.length)
e=t.resetDateToMin(e,this.categoryAxis.minPeriod,1),a=this.getClosestIndex(a,"time",e.getTime(),!1,0,a.length),this.zoom(s,a)}else this.zoom(i.getTime(),e.getTime())},zoomToCategoryValues:function(t,i){this.chartData&&this.zoom(this.getCategoryIndexByValue(t),this.getCategoryIndexByValue(i))},formatPeriodString:function(i,e){if(e){e.periodDataItem={},e.periodPercentDataItem={}
var a=["value","open","low","high","close"],s="value open low high close average sum count".split(" "),h=e.valueAxis,o=this.chartData,r=e.numberFormatter
r||(r=this.nf)
for(var n=0;n<a.length;n++){for(var l,d,u,c,m,g,p,f,x,v,b=a[n],A=0,C=0,T=0,y=0,D=this.start;D<=this.end;D++){if(M=o[D]){var S=M.axes[h.id].graphs[e.id]
if(S){if(S.values){var N=S.values[b],M=M.x.categoryAxis
this.rotate?(0>M||M>S.graph.height)&&(N=NaN):(0>M||M>S.graph.width)&&(N=NaN),isNaN(N)||(isNaN(l)&&(l=N),d=N,(isNaN(u)||u>N)&&(u=N),(isNaN(c)||c<N)&&(c=N),m=t.getDecimals(A),M=t.getDecimals(N),A+=N,m=(A=t.roundTo(A,Math.max(m,M)))/++C)}S.percents&&(S=S.percents[b],!isNaN(S))&&(isNaN(g)&&(g=S),p=S,(isNaN(f)||f>S)&&(f=S),(isNaN(x)||x<S)&&(x=S),v=t.getDecimals(T),N=t.getDecimals(S),T+=S,v=(T=t.roundTo(T,Math.max(v,N)))/++y)}}}A={open:l,close:d,high:c,low:u,average:m,sum:A,count:C},T={open:g,close:p,high:x,low:f,average:v,sum:T,count:y},i=t.formatValue(i,A,s,r,b+"\\.",this.usePrefixes,this.prefixesOfSmallNumbers,this.prefixesOfBigNumbers),i=t.formatValue(i,T,s,this.pf,"percents\\."+b+"\\."),e.periodDataItem[b]=A,e.periodPercentDataItem[b]=T}}return t.cleanFromEmpty(i)},formatString:function(i,e,a){if(e){var s=e.graph
if(void 0!==i){if(-1!=i.indexOf("[[category]]")){var h=e.serialDataItem.category
if(this.categoryAxis.parseDates){var o=this.balloonDateFormat,r=this.chartCursor
r&&r.categoryBalloonDateFormat&&(o=r.categoryBalloonDateFormat),-1!=(o=t.formatDate(h,o,this)).indexOf("fff")&&(o=t.formatMilliseconds(o,h)),h=o}i=i.replace(/\[\[category\]\]/g,String(h.replace("$","$$$")))}(h=s.numberFormatter)||(h=this.nf),(r=(o=e.graph.valueAxis).duration)&&!isNaN(e.values.value)&&o.maxInterval&&(r=t.formatDuration(e.values.value,r,"",o.durationUnits,o.maxInterval,h),i=i.replace(RegExp("\\[\\[value\\]\\]","g"),r)),"date"==o.type&&(o=t.formatDate(new Date(e.values.value),s.dateFormat,this),r=RegExp("\\[\\[value\\]\\]","g"),i=i.replace(r,o),o=t.formatDate(new Date(e.values.open),s.dateFormat,this),r=RegExp("\\[\\[open\\]\\]","g"),i=i.replace(r,o)),s="value open low high close total".split(" "),o=this.pf,i=t.formatValue(i,e.percents,s,o,"percents\\."),i=t.formatValue(i,e.values,s,h,"",this.usePrefixes,this.prefixesOfSmallNumbers,this.prefixesOfBigNumbers),-1!=(i=t.formatValue(i,e.values,["percents"],o)).indexOf("[[")&&(i=t.formatDataContextValue(i,e.dataContext)),-1!=i.indexOf("[[")&&e.graph.customData&&(i=t.formatDataContextValue(i,e.graph.customData)),i=t.AmSerialChart.base.formatString.call(this,i,e,a)}return i}},updateChartCursor:function(){t.AmSerialChart.base.updateChartCursor.call(this)
var i=this.chartCursor,e=this.categoryAxis
if(i){var a=i.categoryBalloonAlpha,s=i.categoryBalloonColor,h=i.color
void 0===s&&(s=i.cursorColor)
var o=i.valueZoomable,r=i.zoomable,n=i.valueLineEnabled
if(this.rotate?(i.vLineEnabled=n,i.hZoomEnabled=o,i.vZoomEnabled=r):(i.hLineEnabled=n,i.vZoomEnabled=o,i.hZoomEnabled=r),i.valueLineBalloonEnabled)for(n=0;n<this.valueAxes.length;n++)o=this.valueAxes[n],(r=o.balloon)||(r={}),r=t.extend(r,this.balloon,!0),r.fillColor=s,r.balloonColor=s,r.fillAlpha=a,r.borderColor=s,r.color=h,o.balloon=r
else for(r=0;r<this.valueAxes.length;r++)o=this.valueAxes[r],o.balloon&&(o.balloon=null)
e&&(e.balloonTextFunction=i.categoryBalloonFunction,i.categoryLineAxis=e,e.balloonText=i.categoryBalloonText,i.categoryBalloonEnabled&&((r=e.balloon)||(r={}),(r=t.extend(r,this.balloon,!0)).fillColor=s,r.balloonColor=s,r.fillAlpha=a,r.borderColor=s,r.color=h,e.balloon=r),e.balloon&&(e.balloon.enabled=i.categoryBalloonEnabled))}},addChartScrollbar:function(i){t.callMethod("destroy",[this.chartScrollbar]),i&&(i.chart=this,this.listenTo(i,"zoomed",this.handleScrollbarZoom)),this.rotate?void 0===i.width&&(i.width=i.scrollbarHeight):void 0===i.height&&(i.height=i.scrollbarHeight),i.gridAxis=this.categoryAxis,this.chartScrollbar=i},addValueScrollbar:function(i){t.callMethod("destroy",[this.valueScrollbar]),i&&(i.chart=this,this.listenTo(i,"zoomed",this.handleScrollbarValueZoom),this.listenTo(i,"zoomStarted",this.handleCursorZoomStarted))
var e=i.scrollbarHeight
this.rotate?void 0===i.height&&(i.height=e):void 0===i.width&&(i.width=e),i.gridAxis||(i.gridAxis=this.valueAxes[0]),i.valueAxes=this.valueAxes,this.valueScrollbar=i},removeChartScrollbar:function(){t.callMethod("destroy",[this.chartScrollbar]),this.chartScrollbar=null},removeValueScrollbar:function(){t.callMethod("destroy",[this.valueScrollbar]),this.valueScrollbar=null},handleReleaseOutside:function(i){t.AmSerialChart.base.handleReleaseOutside.call(this,i),t.callMethod("handleReleaseOutside",[this.chartScrollbar,this.valueScrollbar])},update:function(){t.AmSerialChart.base.update.call(this),this.chartScrollbar&&this.chartScrollbar.update&&this.chartScrollbar.update(),this.valueScrollbar&&this.valueScrollbar.update&&this.valueScrollbar.update()},processScrollbars:function(){t.AmSerialChart.base.processScrollbars.call(this)
var i=this.valueScrollbar
i&&((i=t.processObject(i,t.ChartScrollbar,this.theme)).id="valueScrollbar",this.addValueScrollbar(i))},handleValueAxisZoom:function(t){this.handleValueAxisZoomReal(t,this.valueAxes)},zoomOut:function(){t.AmSerialChart.base.zoomOut.call(this),this.zoom(),this.syncGrid()},getNextItem:function(t){var i=t.index,e=this.chartData,a=t.graph
if(i+1<e.length)for(i+=1;i<e.length;i++)if((t=e[i])&&(t=t.axes[a.valueAxis.id].graphs[a.id],!isNaN(t.y)))return t},handleCursorZoomReal:function(t,i,e,a,s){var h,o,r=s.target
this.rotate?(isNaN(t)||isNaN(i)||this.relativeZoomValueAxes(this.valueAxes,t,i)&&this.updateAfterValueZoom(),r.vZoomEnabled&&(h=s.start,o=s.end)):(isNaN(e)||isNaN(a)||this.relativeZoomValueAxes(this.valueAxes,e,a)&&this.updateAfterValueZoom(),r.hZoomEnabled&&(h=s.start,o=s.end)),isNaN(h)||isNaN(o)||((t=this.categoryAxis).parseDates&&!t.equalSpacing?this.zoomToDates(new Date(h),new Date(o)):this.zoomToIndexes(h,o))},handleCursorZoomStarted:function(){if(t=this.valueAxes){var t,i=(t=t[0]).relativeStart,e=t.relativeEnd
t.reversed&&(i=1-t.relativeEnd,e=1-t.relativeStart),this.rotate?(this.startX0=i,this.endX0=e):(this.startY0=i,this.endY0=e)}this.categoryAxis&&(this.start0=this.start,this.end0=this.end,this.startTime0=this.startTime,this.endTime0=this.endTime)},fixCursor:function(){this.chartCursor&&this.chartCursor.fixPosition(),this.prevCursorItem=null},handleCursorMove:function(i){t.AmSerialChart.base.handleCursorMove.call(this,i)
var e=i.target,a=this.categoryAxis
if(i.panning)this.handleCursorHide(i)
else if(this.chartData&&!e.isHidden){var s,h=this.graphs
if(h)if(s=a.xToIndex(this.rotate?i.y:i.x),s=this.chartData[s]){var o,r,n,l
if(e.oneBalloonOnly&&e.valueBalloonsEnabled){var d=1/0
for(o=h.length-1;0<=o;o--)if(r=h[o],r.balloon.enabled&&r.showBalloon&&!r.hidden){if(n=r.valueAxis.id,n=s.axes[n].graphs[r.id],e.showNextAvailable&&isNaN(n.y)&&!(n=this.getNextItem(n)))continue
n=n.y,"top"==r.showBalloonAt&&(n=0),"bottom"==r.showBalloonAt&&(n=this.height)
var u=e.mouseX,c=e.mouseY;(n=this.rotate?Math.abs(u-n):Math.abs(c-n))<d&&(d=n,l=r)}e.mostCloseGraph=l}if(this.prevCursorItem!=s||l!=this.prevMostCloseGraph){for(d=[],o=0;o<h.length;o++)n=(r=h[o]).valueAxis.id,n=s.axes[n].graphs[r.id],e.showNextAvailable&&isNaN(n.y)&&!(n=this.getNextItem(n))&&r.balloon?r.balloon.hide():l&&r!=l?(r.showGraphBalloon(n,e.pointer,!1,e.graphBulletSize,e.graphBulletAlpha),r.balloon.hide(0)):e.valueBalloonsEnabled?(r.balloon.showBullet=e.bulletsEnabled,r.balloon.bulletSize=e.bulletSize/2,i.hideBalloons||(r.showGraphBalloon(n,e.pointer,!1,e.graphBulletSize,e.graphBulletAlpha),r.balloon.set&&d.push({balloon:r.balloon,y:r.balloon.pointToY}))):(r.currentDataItem=n,r.resizeBullet(n,e.graphBulletSize,e.graphBulletAlpha))
e.avoidBalloonOverlapping&&this.arrangeBalloons(d),this.prevCursorItem=s}this.prevMostCloseGraph=l}h=t.fitToBounds(i.x,0,e.width),l=t.fitToBounds(i.y,0,e.height),a.showBalloon(h,l,e.categoryBalloonDateFormat,i.skip),this.updateLegendValues()}},handleCursorHide:function(i){var e
for(t.AmSerialChart.base.handleCursorHide.call(this,i),i=this.categoryAxis,this.prevCursorItem=null,this.updateLegendValues(),i&&i.hideBalloon(),i=this.graphs,e=0;e<i.length;e++)i[e].currentDataItem=null},handleCursorPanning:function(i){var e,a,s,h=i.target,o=i.deltaX,r=i.deltaY,n=i.delta2X,l=i.delta2Y
if(i=!1,this.rotate){isNaN(n)&&(n=o,i=!0)
var d=(u=this.endX0)-(e=this.startX0),u=u-d*n,c=d
i||(c=0),i=t.fitToBounds(e-d*o,0,1-c)}else isNaN(l)&&(l=r,i=!0),u=this.endY0,e=this.startY0,d=u-e,u+=d*r,c=d,i||(c=0),i=t.fitToBounds(e+d*l,0,1-c)
e=t.fitToBounds(u,c,1),h.valueZoomable&&(a=this.relativeZoomValueAxes(this.valueAxes,i,e)),e=this.categoryAxis,this.rotate&&(o=r,n=l),i=!1,isNaN(n)&&(n=o,i=!0),h.zoomable&&(0<Math.abs(o)||0<Math.abs(n))&&(e.parseDates&&!e.equalSpacing?(l=this.startTime0,n*=e=(r=this.endTime0)-l,d=this.firstTime,u=this.lastTime,c=e,i||(c=0),i=Math.round(t.fitToBounds(l-e*o,d,u-c)),n=Math.round(t.fitToBounds(r-n,d+c,u)),(this.startTime!=i||this.endTime!=n)&&(s={chart:this,target:h,type:"zoomed",start:i,end:n},this.skipZoomed=!0,h.fire(s),this.zoom(i,n),s=!0)):(l=this.start0,e=(r=this.end0)-l,o=Math.round(e*o),n=Math.round(e*n),d=this.chartData.length-1,i||(e=0),i=t.fitToBounds(l-o,0,d-e),e=t.fitToBounds(r-n,e,d),(this.start!=i||this.end!=e)&&(this.skipZoomed=!0,h.fire({chart:this,target:h,type:"zoomed",start:i,end:e}),this.zoom(i,e),s=!0))),!s&&a&&this.updateAfterValueZoom()},arrangeBalloons:function(t){var i=this.plotAreaHeight
t.sort(this.compareY)
var e,a,s,h=this.plotAreaWidth,o=t.length
for(e=0;e<o;e++)a=t[e].balloon,a.setBounds(0,0,h,i),a.restorePrevious(),a.draw(),i=a.yPos-3
for(t.reverse(),e=0;e<o;e++){i=(a=t[e].balloon).bottom
var r=a.bottom-a.yPos
0<e&&i-r<s+3&&a.setBounds&&(a.setBounds(0,s+3,h,s+r+3),a.restorePrevious(),a.draw()),a.set&&a.set.show(),s=a.bottom}},compareY:function(t,i){return t.y<i.y?1:-1}})}(),function(){var t=window.AmCharts
t.Cuboid=t.Class({construct:function(t,i,e,a,s,h,o,r,n,l,d,u,c,m,g,p,f){this.set=t.set(),this.container=t,this.h=Math.round(e),this.w=Math.round(i),this.dx=a,this.dy=s,this.colors=h,this.alpha=o,this.bwidth=r,this.bcolor=n,this.balpha=l,this.dashLength=m,this.topRadius=p,this.pattern=g,this.rotate=c,this.bcn=f,c?0>i&&0===d&&(d=180):0>e&&270==d&&(d=90),this.gradientRotation=d,0===a&&0===s&&(this.cornerRadius=u),this.draw()},draw:function(){var i=this.set
i.clear()
var e=this.container,a=e.chart,s=this.w,h=this.h,o=this.dx,r=this.dy,n=this.colors,l=this.alpha,d=this.bwidth,u=this.bcolor,c=this.balpha,m=this.gradientRotation,g=this.cornerRadius,p=this.dashLength,f=this.pattern,x=this.topRadius,v=this.bcn,b=n,A=n
"object"==typeof n&&(b=n[0],A=n[n.length-1])
var C,T,y,D,S,N,M,w,B,z=l
f&&(l=0)
var R,O,I,Z,L=this.rotate
if(0<Math.abs(o)||0<Math.abs(r))if(isNaN(x))M=A,A=t.adjustLuminosity(b,-.2),A=t.adjustLuminosity(b,-.2),C=t.polygon(e,[0,o,s+o,s,0],[0,r,r,0,0],A,l,1,u,0,m),0<c&&(B=t.line(e,[0,o,s+o],[0,r,r],u,c,d,p)),T=t.polygon(e,[0,0,s,s,0],[0,h,h,0,0],A,l,1,u,0,m),T.translate(o,r),0<c&&(y=t.line(e,[o,o],[r,r+h],u,c,d,p)),D=t.polygon(e,[0,0,o,o,0],[0,h,h+r,r,0],A,l,1,u,0,m),S=t.polygon(e,[s,s,s+o,s+o,s],[0,h,h+r,r,0],A,l,1,u,0,m),0<c&&(N=t.line(e,[s,s+o,s+o,s],[0,r,h+r,h],u,c,d,p)),A=t.adjustLuminosity(M,.2),M=t.polygon(e,[0,o,s+o,s,0],[h,h+r,h+r,h,h],A,l,1,u,0,m),0<c&&(w=t.line(e,[0,o,s+o],[h,h+r,h+r],u,c,d,p))
else{var W,V,P
L?(W=h/2,A=o/2,P=h/2,V=s+o/2,O=Math.abs(h/2),R=Math.abs(o/2)):(A=s/2,W=r/2,V=s/2,P=h+r/2+1,R=Math.abs(s/2),O=Math.abs(r/2)),I=R*x,Z=O*x,.1<R&&.1<R&&(C=t.circle(e,R,b,l,d,u,c,!1,O)).translate(A,W),.1<I&&.1<I&&(M=t.circle(e,I,t.adjustLuminosity(b,.5),l,d,u,c,!1,Z)).translate(V,P)}for(l=z,1>Math.abs(h)&&(h=0),1>Math.abs(s)&&(s=0),!isNaN(x)&&(0<Math.abs(o)||0<Math.abs(r))?(n={fill:n=[b],stroke:u,"stroke-width":d,"stroke-opacity":c,"fill-opacity":l},L?(l="M0,0 L"+s+","+(h/2-h/2*x),d=" B",0<s&&(d=" A"),t.VML?l=(l+=d+Math.round(s-I)+","+Math.round(h/2-Z)+","+Math.round(s+I)+","+Math.round(h/2+Z)+","+s+",0,"+s+","+h)+" L0,"+h+(d+Math.round(-R))+","+Math.round(h/2-O)+","+Math.round(R)+","+Math.round(h/2+O)+",0,"+h+",0,0":(l+="A"+I+","+Z+",0,0,0,"+s+","+(h-h/2*(1-x))+"L0,"+h,l+="A"+R+","+O+",0,0,1,0,0"),R=90):(l="M0,0 L"+(d=s/2-s/2*x)+","+h,t.VML?(l="M0,0 L"+d+","+h,d=" B",0>h&&(d=" A"),l+=d+Math.round(s/2-I)+","+Math.round(h-Z)+","+Math.round(s/2+I)+","+Math.round(h+Z)+",0,"+h+","+s+","+h,l+=" L"+s+",0",l+=d+Math.round(s/2+R)+","+Math.round(O)+","+Math.round(s/2-R)+","+Math.round(-O)+","+s+",0,0,0"):(l+="A"+I+","+Z+",0,0,0,"+(s-s/2*(1-x))+","+h+"L"+s+",0",l+="A"+R+","+O+",0,0,1,0,0"),R=180),(e=e.path(l).attr(n)).gradient("linearGradient",[b,t.adjustLuminosity(b,-.3),t.adjustLuminosity(b,-.3),b],R),L?e.translate(o/2,0):e.translate(0,r/2)):e=0===h?t.line(e,[0,s],[0,0],u,c,d,p):0===s?t.line(e,[0,0],[0,h],u,c,d,p):0<g?t.rect(e,s,h,n,l,d,u,c,g,m,p):t.polygon(e,[0,0,s,s,0],[0,h,h,0,0],n,l,d,u,c,m,!1,p),s=isNaN(x)?0>h?[C,B,T,y,D,S,N,M,w,e]:[M,w,T,y,D,S,C,B,N,e]:L?0<s?[C,e,M]:[M,e,C]:0>h?[C,e,M]:[M,e,C],t.setCN(a,e,v+"front"),t.setCN(a,T,v+"back"),t.setCN(a,M,v+"top"),t.setCN(a,C,v+"bottom"),t.setCN(a,D,v+"left"),t.setCN(a,S,v+"right"),C=0;C<s.length;C++)(T=s[C])&&(i.push(T),t.setCN(a,T,v+"element"))
f&&e.pattern(f,NaN,a.path)},width:function(t){isNaN(t)&&(t=0),this.w=Math.round(t),this.draw()},height:function(t){isNaN(t)&&(t=0),this.h=Math.round(t),this.draw()},animateHeight:function(i,e){var a=this
a.animationFinished=!1,a.easing=e,a.totalFrames=i*t.updateRate,a.rh=a.h,a.frame=0,a.height(1),setTimeout(function(){a.updateHeight.call(a)},1e3/t.updateRate)},updateHeight:function(){var i=this
i.frame++
var e=i.totalFrames
i.frame<=e?(e=i.easing(0,i.frame,1,i.rh-1,e),i.height(e),window.requestAnimationFrame?window.requestAnimationFrame(function(){i.updateHeight.call(i)}):setTimeout(function(){i.updateHeight.call(i)},1e3/t.updateRate)):(i.height(i.rh),i.animationFinished=!0)},animateWidth:function(i,e){var a=this
a.animationFinished=!1,a.easing=e,a.totalFrames=i*t.updateRate,a.rw=a.w,a.frame=0,a.width(1),setTimeout(function(){a.updateWidth.call(a)},1e3/t.updateRate)},updateWidth:function(){var i=this
i.frame++
var e=i.totalFrames
i.frame<=e?(e=i.easing(0,i.frame,1,i.rw-1,e),i.width(e),window.requestAnimationFrame?window.requestAnimationFrame(function(){i.updateWidth.call(i)}):setTimeout(function(){i.updateWidth.call(i)},1e3/t.updateRate)):(i.width(i.rw),i.animationFinished=!0)}})}(),function(){var t=window.AmCharts
t.CategoryAxis=t.Class({inherits:t.AxisBase,construct:function(i){this.cname="CategoryAxis",t.CategoryAxis.base.construct.call(this,i),this.minPeriod="DD",this.equalSpacing=this.parseDates=!1,this.position="bottom",this.startOnAxis=!1,this.gridPosition="middle",this.safeDistance=30,this.stickBalloonToCategory=!1,t.applyTheme(this,i,this.cname)},draw:function(){t.CategoryAxis.base.draw.call(this),this.generateDFObject()
var i=this.chart.chartData
if(this.data=i,this.labelRotationR=this.labelRotation,this.type=null,t.ifArray(i)){var e,a=this.chart
"scrollbar"!=this.id?(t.setCN(a,this.set,"category-axis"),t.setCN(a,this.labelsSet,"category-axis"),t.setCN(a,this.axisLine.axisSet,"category-axis")):this.bcn=this.id+"-"
var s,h,o,r,n,l,d=this.start,u=this.labelFrequency,c=0,m=this.end-d+1,g=this.gridCountR,p=this.showFirstLabel,f=this.showLastLabel,x="",v=(x=t.extractPeriod(this.minPeriod),t.getPeriodDuration(x.period,x.count)),b=this.rotate,A=this.firstDayOfWeek,C=this.boldPeriodBeginning
e=t.resetDateToMin(new Date(i[i.length-1].time+1.05*v),this.minPeriod,1,A).getTime(),this.firstTime=a.firstTime,this.endTime>e&&(this.endTime=e),l=this.minorGridEnabled,o=this.gridAlpha
var T=0,y=0
if(this.widthField)for(e=this.start;e<=this.end;e++)if(n=this.data[e]){var D=Number(this.data[e].dataContext[this.widthField])
isNaN(D)||(T+=D,n.widthValue=D)}if(this.parseDates&&!this.equalSpacing)this.lastTime=i[i.length-1].time,this.maxTime=t.resetDateToMin(new Date(this.lastTime+1.05*v),this.minPeriod,1,A).getTime(),this.timeDifference=this.endTime-this.startTime,this.parseDatesDraw()
else if(this.parseDates){if(this.parseDates&&this.equalSpacing){if(c=this.start,this.startTime=this.data[this.start].time,this.endTime=this.data[this.end].time,this.timeDifference=this.endTime-this.startTime,u=(e=this.choosePeriod(0)).period,h=e.count,(e=t.getPeriodDuration(u,h))<v&&(u=x.period,h=x.count,e=v),"WW"==(o=u)&&(o="DD"),this.currentDateFormat=this.dateFormatsObject[o],this.stepWidth=this.getStepWidth(m),g=Math.ceil(this.timeDifference/e)+1,x=t.resetDateToMin(new Date(this.startTime-e),u,h,A).getTime(),this.cellWidth=this.getStepWidth(m),d=-1,(m=Math.round(x/e))/2==Math.round(m/2)&&(d=-2,x-=e),(m=this.start)/2==Math.round(m/2)&&m--,0>m&&(m=0),(y=this.end+2)>=this.data.length&&(y=this.data.length),i=!1,i=!p,this.previousPos=-1e3,20<this.labelRotationR&&(this.safeDistance=5),D=m,this.data[m].time!=t.resetDateToMin(new Date(this.data[m].time),u,h,A).getTime()){v=0
var S=x
for(e=m;e<y;e++)n=this.data[e].time,this.checkPeriodChange(u,h,n,S)&&(v++,2<=v&&(D=e,e=y),S=n)}if(l&&1<h&&(n=this.chooseMinorFrequency(h),t.getPeriodDuration(u,n)),0<this.gridCountR)for(e=m;e<y;e++)n=this.data[e].time,this.checkPeriodChange(u,h,n,x)&&e>=D&&(m=this.getCoordinate(e-this.start),l=!1,this.nextPeriod[o]&&(l=this.checkPeriodChange(this.nextPeriod[o],1,n,x,o))&&t.resetDateToMin(new Date(n),this.nextPeriod[o],1,A).getTime()!=n&&(l=!1),v=!1,l&&this.markPeriodChange?(l=this.dateFormatsObject[this.nextPeriod[o]],v=!0):l=this.dateFormatsObject[o],x=t.formatDate(new Date(n),l,a),(e==d&&!p||e==g&&!f)&&(x=" "),i?i=!1:(C||(v=!1),m-this.previousPos>this.safeDistance*Math.cos(this.labelRotationR*Math.PI/180)&&(this.labelFunction&&(x=this.labelFunction(x,new Date(n),this,u,h,r)),this.boldLabels&&(v=!0),l=(s=new this.axisItemRenderer(this,m,x,void 0,void 0,void 0,void 0,v)).graphics(),this.pushAxisItem(s),l=l.getBBox().width,t.isModern||(l-=m),this.previousPos=m+l)),r=x=n)}}else if(this.cellWidth=this.getStepWidth(m),m<g&&(g=m),c+=this.start,this.stepWidth=this.getStepWidth(m),0<g)for(A=Math.floor(m/g),n=this.chooseMinorFrequency(A),m=c,m/2==Math.round(m/2)&&m--,0>m&&(m=0),C=0,this.widthField&&(m=this.start,A=1),this.end-m+1>=this.autoRotateCount&&(this.labelRotationR=this.autoRotateAngle),e=m;e<=this.end+2;e++){if(g=!1,0<=e&&e<this.data.length?(x=(h=this.data[e]).category,g=h.forceShow):x="",l&&!isNaN(n)){if(e/n!=Math.round(e/n)&&!g)continue
e/A==Math.round(e/A)||g||(this.gridAlpha=this.minorGridAlpha,x=void 0)}else if(e/A!=Math.round(e/A)&&!g)continue
m=this.getCoordinate(e-c),g=0,"start"==this.gridPosition&&(m-=this.cellWidth/2,g=this.cellWidth/2),s=!0,r=g,"start"==this.tickPosition&&(r=0,s=!1,g=0),(e==d&&!p||e==this.end&&!f)&&(x=void 0),Math.round(C/u)!=C/u&&(x=void 0),C++,i=this.cellWidth,b&&(i=NaN,this.ignoreAxisWidth||!a.autoMargins)&&(i="right"==this.position?a.marginRight-this.titleWidth:a.marginLeft-this.titleWidth,i-=this.tickLength+10),this.labelFunction&&h&&(x=this.labelFunction(x,h,this)),x=t.fixBrakes(x),v=!1,this.boldLabels&&(v=!0),e>this.end&&"start"==this.tickPosition&&(x=" "),this.rotate&&this.inside&&(g-=2),isNaN(h.widthValue)||(h.percentWidthValue=h.widthValue/T*100,m=y,y+=i=this.rotate?this.height*h.widthValue/T:this.width*h.widthValue/T,r=g=i/2),(s=new this.axisItemRenderer(this,m,x,s,i,g,void 0,v,r,!1,h.labelColor,h.className)).serialDataItem=h,this.pushAxisItem(s),this.gridAlpha=o}for(e=p=0;e<this.data.length;e++)(n=this.data[e])&&(this.parseDates&&!this.equalSpacing?(f=n.time,d=this.cellWidth,"MM"==this.minPeriod&&(d=864e5*t.daysInMonth(new Date(f))*this.stepWidth,n.cellWidth=d),f=Math.round((f-this.startTime)*this.stepWidth+d/2)):f=this.getCoordinate(e-c),n.x[this.id]=f)
if(this.widthField)for(e=this.start;e<=this.end;e++)n=this.data[e],d=n.widthValue,n.percentWidthValue=d/T*100,this.rotate?(f=this.height*d/T/2+p,p=this.height*d/T+p):(f=this.width*d/T/2+p,p=this.width*d/T+p),n.x[this.id]=f
for(T=this.guides.length,e=0;e<T;e++)p=this.guides[e],A=A=A=l=d=NaN,f=p.above,p.toCategory&&(A=a.getCategoryIndexByValue(p.toCategory),isNaN(A)||(d=this.getCoordinate(A-c),p.expand&&(d+=this.cellWidth/2),s=new this.axisItemRenderer(this,d,"",!0,NaN,NaN,p),this.pushAxisItem(s,f))),p.category&&(A=a.getCategoryIndexByValue(p.category),isNaN(A)||(l=this.getCoordinate(A-c),p.expand&&(l-=this.cellWidth/2),A=(d-l)/2,s=new this.axisItemRenderer(this,l,p.label,!0,NaN,A,p),this.pushAxisItem(s,f))),C=a.dataDateFormat,p.toDate&&(!C||p.toDate instanceof Date||(p.toDate=p.toDate.toString()+" |"),p.toDate=t.getDate(p.toDate,C),this.equalSpacing?(A=a.getClosestIndex(this.data,"time",p.toDate.getTime(),!1,0,this.data.length-1),isNaN(A)||(d=this.getCoordinate(A-c))):d=(p.toDate.getTime()-this.startTime)*this.stepWidth,s=new this.axisItemRenderer(this,d,"",!0,NaN,NaN,p),this.pushAxisItem(s,f)),p.date&&(!C||p.date instanceof Date||(p.date=p.date.toString()+" |"),p.date=t.getDate(p.date,C),this.equalSpacing?(A=a.getClosestIndex(this.data,"time",p.date.getTime(),!1,0,this.data.length-1),isNaN(A)||(l=this.getCoordinate(A-c))):l=(p.date.getTime()-this.startTime)*this.stepWidth,A=(d-l)/2,s=!0,p.toDate&&(s=!1),s="H"==this.orientation?new this.axisItemRenderer(this,l,p.label,s,2*A,NaN,p):new this.axisItemRenderer(this,l,p.label,!1,NaN,A,p),this.pushAxisItem(s,f)),s&&(A=s.label)&&this.addEventListeners(A,p),(0<d||0<l)&&(A=!1,this.rotate?(d<this.height||l<this.height)&&(A=!0):(d<this.width||l<this.width)&&(A=!0),A&&(l=(d=new this.guideFillRenderer(this,l,d,p)).graphics(),this.pushAxisItem(d,f),p.graphics=l,l.index=e,this.addEventListeners(l,p)));(a=a.chartCursor)&&(b?a.fixHeight(this.cellWidth):(a.fixWidth(this.cellWidth),a.fullWidth&&this.balloon&&(this.balloon.minWidth=this.cellWidth))),this.previousHeight=N}this.axisCreated=!0,this.set.translate(this.x,this.y),this.labelsSet.translate(this.x,this.y),this.labelsSet.show(),this.positionTitle(),(b=this.axisLine.set)&&b.toFront()
var N=this.getBBox().height
2<N-this.previousHeight&&this.autoWrap&&!this.parseDates&&(this.axisCreated=this.chart.marginsUpdated=!1)},xToIndex:function(i){var e,a,s=this.data,h=this.chart,o=h.rotate,r=this.stepWidth
if(this.parseDates&&!this.equalSpacing)i=this.startTime+Math.round(i/r)-this.minDuration()/2,e=h.getClosestIndex(s,"time",i,!1,this.start,this.end+1)
else if(this.widthField)for(h=1/0,r=this.start;r<=this.end;r++){var n=this.data[r]
n&&((n=Math.abs(n.x[this.id]-i))<h&&(h=n,e=r))}else this.startOnAxis||(i-=r/2),e=this.start+Math.round(i/r)
return s[e=t.fitToBounds(e,0,s.length-1)]&&(a=s[e].x[this.id]),o?a>this.height+1&&e--:a>this.width+1&&e--,0>a&&e++,t.fitToBounds(e,0,s.length-1)},dateToCoordinate:function(t){return this.parseDates&&!this.equalSpacing?(t.getTime()-this.startTime)*this.stepWidth:this.parseDates&&this.equalSpacing?(t=this.chart.getClosestIndex(this.data,"time",t.getTime(),!1,0,this.data.length-1),this.getCoordinate(t-this.start)):NaN},categoryToCoordinate:function(t){return this.chart?this.parseDates?this.dateToCoordinate(new Date(t)):(t=this.chart.getCategoryIndexByValue(t),isNaN(t)?void 0:this.getCoordinate(t-this.start)):NaN},coordinateToDate:function(t){return this.equalSpacing?(t=this.xToIndex(t),new Date(this.data[t].time)):new Date(this.startTime+t/this.stepWidth)},coordinateToValue:function(t){if(t=this.xToIndex(t),t=this.data[t])return this.parseDates?t.time:t.category},getCoordinate:function(t){return t*=this.stepWidth,this.startOnAxis||(t+=this.stepWidth/2),Math.round(t)},formatValue:function(i,e){return e||(e=this.currentDateFormat),this.parseDates&&(i=t.formatDate(new Date(i),e,this.chart)),i},showBalloonAt:function(t,i){return void 0===i&&(i=this.parseDates?this.dateToCoordinate(new Date(t)):this.categoryToCoordinate(t)),this.adjustBalloonCoordinate(i)},formatBalloonText:function(i,e,a){var s="",h="",o=this.chart,r=this.data[e]
if(r)if(this.parseDates)s=t.formatDate(r.category,a,o),e=t.changeDate(new Date(r.category),this.minPeriod,1),h=t.formatDate(e,a,o),-1!=s.indexOf("fff")&&(s=t.formatMilliseconds(s,r.category),h=t.formatMilliseconds(h,e))
else{var n
this.data[e+1]&&(n=this.data[e+1]),s=t.fixNewLines(r.category),n&&(h=t.fixNewLines(n.category))}return(i=i.replace(/\[\[category\]\]/g,String(s))).replace(/\[\[toCategory\]\]/g,String(h))},adjustBalloonCoordinate:function(t,i){var e=this.xToIndex(t),a=this.chart.chartCursor
if(this.stickBalloonToCategory){var s=this.data[e]
s&&(t=s.x[this.id]),this.stickBalloonToStart&&(t-=this.cellWidth/2)
var h=0
if(a){var o=a.limitToGraph
if(o){var r=o.valueAxis.id
o.hidden||(h=s.axes[r].graphs[o.id].y)}this.rotate?("left"==this.position?(o&&(h-=a.width),0<h&&(h=0)):0>h&&(h=0),a.fixHLine(t,h)):("top"==this.position?(o&&(h-=a.height),0<h&&(h=0)):0>h&&(h=0),a.fullWidth&&(t+=1),a.fixVLine(t,h))}}return a&&!i&&(a.setIndex(e),this.parseDates&&a.setTimestamp(this.coordinateToDate(t).getTime())),t}})}()
